language: python

cache:
  directories:
  - "~/.platformio"

install:
- pip install -U platformio
- wget http://www.airspayce.com/mikem/arduino/AccelStepper/AccelStepper-1.56.zip
- unzip AccelStepper-1.56.zip -d /tmp

env:
- BOARD=uno
- BOARD=leonardo
- BOARD=micro
- BOARD=megaatmega2560
- BOARD=due
- BOARD=yun
- BOARD=genuino101
- BOARD=zero

script:
- set -eo pipefail;
  for e in examples/*; do
    platformio ci --board=$BOARD --lib=. --lib=/tmp/AccelStepper $e/*;
  done
